tap "homebrew/bundle"
tap "homebrew/services"
brew "autojump"
brew "docker-compose"
brew "fzf"
brew "mysql@8.0", restart_service: true
brew "neovim"
brew "rbenv"
brew "ripgrep"
brew "tmux"
brew "vim"
cask "docker"
